
--UNDERGRAD PS,PL,NR NO SGASTDN
SELECT (RORALGS_AMT + 300)
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
	WHEN (X.SARADAP_STYP_CODE = 'F' and RORPRST_XHS_LOCK_IND = 'Y' and RORPRST_XHS = '3') THEN '1' -- off campus
	WHEN (X.SARADAP_STYP_CODE = 'F' and RORPRST_XHS_LOCK_IND = 'Y' and RORPRST_XHS in ('1', '4')) THEN '3' -- family/relative
	WHEN (X.SARADAP_STYP_CODE <> 'F' and RORPRST_XHS = '3') THEN '1' -- off campus
	WHEN (X.SARADAP_STYP_CODE <> 'F' and RORPRST_XHS in ('1', '4')) THEN '3' -- family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND (
    X.SARADAP_COLL_CODE_1 IN ('PS','PL')
    OR X.SARADAP_PROGRAM_1 IN ('NR041','NR02','TEAC03', 'NR06')
) 
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD 	
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)		
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
) 
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END
