--LAW NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT 
    FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5

AND CASE
	WHEN X.SGBSTDN_FULL_PART_IND = 'P' THEN '8TO11'
-- assumed to add fallback to full part ind = F, confirm with Jessica/Janice (jd 04132026)
	WHEN (X.SGBSTDN_FULL_PART_IND = 'F' OR X.SGBSTDN_FULL_PART_IND IS NULL) THEN '12+'
END = RORALGS_KEY_12

 -- max sgbstdn term <= passed period	
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND RORALGS_AIDY_CODE = :AIDY
AND X.SGBSTDN_PIDM = :PIDM
--END
