
-- sequence 2: SGBSTDN SEQUENCE
SELECT case
	when (a.SGBSTDN_FULL_PART_IND = 'P' and a.SGBSTDN_LEVL_CODE = 'PL') then (RORALGS_AMT / 2)
	else RORALGS_AMT
end
FROM SGBSTDN a
CROSS JOIN RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS' --check on component code
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = a.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > a.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> a.SGBSTDN_PROGRAM_1
)
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- ;
