
--GRAD PA/SLH WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, SGRCHRT X, RORALGS, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

AND CASE -- major code
    WHEN X.SGBSTDN_MAJR_CODE_1 = 'PA' THEN 'PA'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'SLH' THEN 'SLH'
END = RORALGS_KEY_9

--NEED TO HAVE TEN ROWS ON RORALGS, A FALL AND SPRING ROW FOR EACH COHORT CODE PA2024, PA2025, PA2026, 2025SLH, 2026SLH			
AND CASE -- cohort code
    WHEN X.SGRCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_END_YEAR) THEN ('PA' || ROBINST_AIDY_END_YEAR)                     --PA2026 FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_START_YEAR) THEN ('PA' || ROBINST_AIDY_START_YEAR)                 --PA2025 FOR FY26
	WHEN X.SGRCHRT_CHRT_CODE = ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1)) THEN ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1))     --PA2024 FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2026SLH FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2025SLH FOR FY26
END = RORALGS_KEY_11

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	-- max cohort term <= passed period
AND X.SGRCHRT_TERM_CODE_EFF = (
    SELECT MAX(Y.SGRCHRT_TERM_CODE_EFF)
    FROM SGRCHRT Y
    WHERE Y.SGRCHRT_PIDM = X.SGRCHRT_PIDM
    AND Y.SGRCHRT_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRCHRT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
--END
