
--GRAD PA/SLH NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, SARCHRT, RORALGS, STVAPDC, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

AND CASE -- major code
    WHEN X.SARADAP_MAJR_CODE_1 = 'PA' THEN 'PA'
	WHEN X.SARADAP_MAJR_CODE_1 = 'SLH' THEN 'SLH'
END = RORALGS_KEY_9

--Likely only need one of these for new students, but need to check with SLU
AND CASE -- cohort code
    WHEN SARCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_END_YEAR) THEN ('PA' || ROBINST_AIDY_END_YEAR)                     --PA2026 FOR FY26
    WHEN SARCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_START_YEAR) THEN ('PA' || ROBINST_AIDY_START_YEAR)                 --PA2025 FOR FY26
	WHEN SARCHRT_CHRT_CODE = ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1)) THEN ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1))     --PA2024 FOR FY26
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2026SLH FOR FY26
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2025SLH FOR FY26
END = RORALGS_KEY_11

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12

-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 

AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARCHRT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARCHRT_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARCHRT_PIDM
AND X.SARADAP_PIDM = :PIDM
--END

