--GRAD WITH SELECT EDUCATION PROGRAM CODES NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE12' THEN 'ELCE12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE13' THEN 'ELCE13'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE14' THEN 'ELCE14'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE16' THEN 'ELCE16'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE17' THEN 'ELCE17'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE18' THEN 'ELCE18'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC12' THEN 'TEAC12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC13' THEN 'TEAC13'         --$450 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EALM41' THEN 'ELAM41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI11' THEN 'EDI11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL11' THEN 'EDL11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL13' THEN 'EDL13'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL18' THEN 'EDL18'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDE41' THEN 'EDE41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EIP41' THEN 'EIP41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE21' THEN 'ELCE21'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE22' THEN 'ELCE22'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE23' THEN 'ELCE23'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPP11' THEN 'EPP11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'HESA11' THEN 'HESA11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC11' THEN 'TEAC11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC14' THEN 'TEAC14'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC15' THEN 'TEAC15'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC17' THEN 'TEAC17'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC18' THEN 'TEAC18'         --$690 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL15' THEN 'EDL15'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL21' THEN 'EDL21'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL22' THEN 'EDL22'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL221' THEN 'EDL221'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL222' THEN 'EDL222'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL223' THEN 'EDL223'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL225' THEN 'EDL225'         --$990 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDF22' THEN 'EDF22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDHA22' THEN 'EDHA22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI21' THEN 'EDI21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL24' THEN 'EDL24'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDS22' THEN 'EDS22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPE21' THEN 'EPE21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'UNCL883' THEN 'UNCL883'         --$1,400 for FY26
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END