--GRAD WITH SELECT EDUCATION PROGRAM CODES NO SGASTDN ENROLLED
SELECT (RORALGS_AMT * 6)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE12' THEN 'ELCE12'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE13' THEN 'ELCE13'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE14' THEN 'ELCE14'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE16' THEN 'ELCE16'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE17' THEN 'ELCE17'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE18' THEN 'ELCE18'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC12' THEN 'TEAC12'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC13' THEN 'TEAC13'         --$450 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EALM41' THEN 'ELAM41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDI11' THEN 'EDI11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL11' THEN 'EDL11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL13' THEN 'EDL13'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL18' THEN 'EDL18'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDE41' THEN 'EDE41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EIP41' THEN 'EIP41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE21' THEN 'ELCE21'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE22' THEN 'ELCE22'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE23' THEN 'ELCE23'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EPP11' THEN 'EPP11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'HESA11' THEN 'HESA11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC11' THEN 'TEAC11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC14' THEN 'TEAC14'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC15' THEN 'TEAC15'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC17' THEN 'TEAC17'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC18' THEN 'TEAC18'         --$690 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EDL15' THEN 'EDL15'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL21' THEN 'EDL21'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL22' THEN 'EDL22'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL221' THEN 'EDL221'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL222' THEN 'EDL222'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL223' THEN 'EDL223'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL225' THEN 'EDL225'         --$990 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EDF22' THEN 'EDF22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDHA22' THEN 'EDHA22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDI21' THEN 'EDI21'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL24' THEN 'EDL24'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDS22' THEN 'EDS22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EPE21' THEN 'EPE21'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'UNCL883' THEN 'UNCL883'         --$1,400 for FY26
END = RORALGS_KEY_9		
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END